### PR TITLE
[FIX]website_apps_store: fix the shop pager

### PR DESCRIPTION
**Pull request by bizzappdev**
remove not needed route which was causing the problem for paging.

### CODE REVIEW

**Comment by bizzappdev** [comment]
@elicoidal  @oscarolar @StephanRozendaal @sbidoul can you please review

**Comment by elicoidal** [comment]
I cannot help here :smile:

**Review by sbidoul — APPROVED** [review]
That's what the Odoo doc says to do so I guess it's ok :)

Let me know if you need me to merge deploy anything during the sprint.

**Review by pedrobaeza — APPROVED** [review]
Please deploy it.

**Comment by bizzappdev** [comment]
@sbidoul can you please deploy this?

**Pull request merged**
