### PR TITLE
[FIX]website_apps_store: attribute value change was not changing the …

### LINKED ISSUE #56: Link target incorrect in repository reference
If I change the version in the module page, the text of the link changes, but not the target:

Selección_035

### PR DESCRIPTION
**Pull request by bizzappdev**
…href for the repository.

Fixes #56

### CODE REVIEW

**Comment by bizzappdev** [comment]
@pedrobaeza  this is the fix for #56

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul can you deploy it?

**Comment by sbidoul** [comment]
deployed

**Comment by pedrobaeza** [comment]
Tried and working!

**Pull request merged**
