### PR TITLE
[FIX]CSS module description

### PR DESCRIPTION
**Pull request by bizzappdev**
Fix issue #37 
Needs review from CSS Experts

### CODE REVIEW

**Comment by elicoidal** [comment]
@pedrobaeza do you have any recommendation for the review?

**Comment by pedrobaeza** [comment]
@Yajo can you take a look?

**Comment by yajo** [comment]
I don't know how to get to the bug this is supposed to fix. :confused:

**Comment by bizzappdev** [comment]
> I don't know how to get to the bug this is supposed to fix.

hello !
the problem is for SVG file from readme.rst was consuming extra space. to remove that
added ss change
.desc_rst .document > :first-child {
    display: none;
}
E.G
https://odoo-community.org/shop/product/management-system-1617?search=audit+log

selection_009

but now problem is that is if the first child is not from the reference class it will also be applied to the entire document  and which cause the entire document not visible

https://odoo-community.org/shop/product/import-paypal-bank-statements-4542
selection_010

so to make it only effeted for reference class I have did commit in this PR

**Review by yajo — CHANGES_REQUESTED** [review]
OK I see. Indeed this should fix that problem. However, the question is: why does this...

```restructuredtext
.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
   :alt: License: AGPL-3
```

...  become this ...

```html
<a class="reference external image-reference" href="http://www.gnu.org/licenses/agpl-3.0-standalone.html">
  <object type="image/svg+xml">License: AGPL-3</object>
</a>
```

... instead of this?

```html

<a class="reference external image-reference" href="http://www.gnu.org/licenses/agpl-3.0-standalone.html">
  <img src="https://img.shields.io/badge/licence-AGPL--3-blue.svg" alt="License: AGPL-3"/>
</a>
```

Because, after all, what we want is that the badge (and any other part of the README) displays correctly, isn't it?

**Comment by bizzappdev** [comment]
from the interface-github the module description has been generated automatically. 
based on https://github.com/OCA/interface-github/blob/11.0/github_connector_odoo/models/odoo_module_version.py#L197

I will have to debug for the reason why it is not generated properly. 
but meanwhile IMO till then This should be go live.

**Review by yajo — APPROVED** [review]
OK, let's merge it as an intermediate fix.

**Comment by bizzappdev** [comment]
@sbidoul can you please deploy this?

**Comment by sbidoul** [comment]
@bizzappdev deployed. And we have readmes: https://odoo-community.org/shop/product/mis-builder-1636?search=mis+builder :tada:

**Comment by pedrobaeza** [comment]
Icon is not changed according version, or all versions have the Acsone logo? Remember that no branding should be put on OCA modules, so I beg you to change it ASAP.

**Comment by sbidoul** [comment]
@pedrobaeza no idea where that icon comes from. Here is the icon in github: https://github.com/OCA/mis-builder/blob/10.0/mis_builder/static/description/icon.png

**Comment by pedrobaeza** [comment]
Yeah, curious... I think the image has been cached somehow when creating the product. I'm changing it manually, but we have to also see if we have a different image per version if this is preserved.

**Comment by pedrobaeza** [comment]
Hehe, it doesn't work... I'm not able to change it on backend.

**Comment by sbidoul** [comment]
#48 to track the icon issue.

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
