### PR TITLE
[FIX]website_apps_store: alignment fixes

### PR DESCRIPTION
**Pull request by bizzappdev**
Solve the alignment problem
OLD:
Selection_173

NEW: 
Selection_174

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Check if tests depends on previous DOM structure.

**Comment by bizzappdev** [comment]
Test case is not failing because of my commit but because of something has changed at the interface-github/github_connector_odoo/models/odoo_module_version.py

from  https://travis-ci.org/OCA/apps-store/jobs/619607872#L1232 it is accessing version.repository_branch_id.local_path and that is failing the test case for apps_product_creator and with the same reason, apps_download demo data is not able to be loaded. https://travis-ci.org/OCA/apps-store/jobs/619607872#L1508 that is why JS tour test cases are failing.

**Comment by pedrobaeza** [comment]
OK, I will check to see. Thanks for the patch.

**Review by Tardo — APPROVED** [review]
Thanks!

**Pull request merged**
