### PR TITLE
[13.0][MIG] apps_download: Migration to 13.0

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT23177

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Code review

I have split the black, isort, prettier diff into a separated commit. @Tardo please remember to do the proper steps for migrating to v13.

**Comment by CarlosRoca13** [comment]
I catch two errors when I was trying to access to github section. You can see it on the attached gif
Peek 06-08-2020 09-17

**Comment by Tardo** [comment]
@CarlosRoca13 sorry, i can't reproduce the issue... ¿can you share the error? Use "debug=assets", CTRL+SHIFT+I to copy the error message from the browser console.
Thanks!

EDIT: I saw the error in runbot.

**Comment by Tardo** [comment]
Ok @CarlosRoca13 it's a problem with the demo data of "apps_download". Runbot can't install the module because needs a custom configuration parameter but the demo data is loaded and dependencies are in a "unstable state" (like 'apps_product_creator') all views of this dependency are loaded but the module is not really installed, so new fields are not loaded (like "product_qty").

**Review by CarlosRoca13 — APPROVED** [review]
Ok, so LGTM :+1:

**Pull request merged**
