### PR TITLE
11.0 issue #50 add the module technical name in front page

### PR DESCRIPTION
**Pull request by bizzappdev**
#50

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM. Functional test
Thanks!

**Review by StephanRozendaal — APPROVED** [review]
LGTM!
Does this need a version number update?

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by bizzappdev** [comment]
rebase done. you can proceed further for merge.

**Comment by elicoidal** [comment]
@sbidoul please deploy at your convenience :smiley:

**Comment by sbidoul** [comment]
@elicoidal @bizzappdev deployed

**Pull request merged**
