### PR TITLE
Update .travis.yml: Transifex Secure

### PR DESCRIPTION
**Pull request by elicoidal**
@espo-tony @astirpe @bizzappdev

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
@elicoidal it seems that is still not fixed. I'm actually on holidays, so for me is difficult to track the progress.  Once it will be fixed, consider my approval as a valid one.

**Comment by elicoidal** [comment]
Hi @astirpe dont worry: I will follow up :smile: 
Enjoy!

**Comment by elicoidal** [comment]
@pedrobaeza sorry I could not solve this one. What did I do wrong?

**Comment by lasley** [comment]
@elicoidal can you paste your `travis encrypt` command, with the password privatized using `*`s?

**Comment by elicoidal** [comment]
@lasley @pedrobaeza generated the secret for me (I do not know the steps to get it or how to answer your question)

**Comment by pedrobaeza** [comment]
I got confused with the password. Now it's correct. Fast-tracking it.

**Pull request merged**
