### PR TITLE
[13.0][MIG] website_apps_store: Migration to 13.0

### PR DESCRIPTION
**Pull request by Tardo**
** Touched 'apps_product_creator' to consider the product attributes changes made on 13.0

**Depends on** https://github.com/OCA/apps-store/pull/75

cc @tecnativa TT23205

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why have you migrate it without adding the pre-commit stuff isolately in a separate commit? As this one is depending on the other PR, I'm not going to review it yet waiting for that step, as the migration diff is not easy to be reviewed mixed with the formatting stuff.

**Comment by Tardo** [comment]
Sorry, changes done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Code review

**Comment by pedrobaeza** [comment]
@CarlosRoca13 please review

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
