### PR TITLE
[11.0] remove default icon for products in the shop

### PR DESCRIPTION
**Pull request by StephanRozendaal**
Change includes:
 - Remove the default icon that is show when a product is an Odoo module, and is does not have an image, we're going to set a default image on each product instead.

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM

**Comment by elicoidal** [comment]
@RoelAdriaans @oscarolar @bizzappdev please review

**Review by oscarolar — APPROVED** [review]
👍

**Comment by elicoidal** [comment]
@gurneyalex could you deploy at your convenience?

**Comment by bizzappdev** [comment]
@elicoidal IMO this is depending upon https://github.com/OCA/interface-github/pull/27
So once both are merged we can proceed for the deployment not now.

@StephanRozendaal  please confirm

**Comment by west-it-solutions-odoo** [comment]
@bizzappdev Yes this depends on the mentioned PR.

**Comment by StephanRozendaal** [comment]
@bizzappdev Yes this depends on the merge of mentioned PR.

Sorry was on wrong account before ;)

**Comment by pedrobaeza** [comment]
@sbidoul can you deploy this in OCA instance?

**Comment by bizzappdev** [comment]
No, not now do not deploy on production. The depending or is still in needs review and open. https://github.com/OCA/interface-github/pull/27

**Comment by sbidoul** [comment]
too late, I just deployed it...

**Pull request merged**
